version: '3'

services:
  server:
    container_name: KC_SERVER_CONTAINER
    build: './server'
    volumes:
      - ./server/:/node-app
      - ./server/node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  client:
    container_name: KC_CLIENT_CONTAINER
    image: node:latest
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - '8080:8080'
    command: npm run serve

  db:
    image: 'mongo'
    container_name: KC_MONGODB_CONTAINER
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db